services:
  - type: web
    name: ecademy-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: development
      - key: MONGODB_URL
        value: mongodb+srv://s3935748:duzF9abNcGRq8RhT@ecademy.cj68zsr.mongodb.net/
      - key: FRONTEND_URL
        value: https://ecademy-deploy.vercel.app
      - key: PORT
        value: 3001 
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://ecademy-deploy.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization, X-Requested-With, Accept, Origin
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"